### ISSUE TITLE
crash with better with mods

### ISSUE THREAD

**Issue by 0Navis0** [ejektaflex/NaturalPledge#6]
I get this crash at the game loading with Better With Mods https://paste.dimdev.org/eyogukuzag.mccrash

**Comment by primetoxinz** [comment]
BWM dev here. This is something we've dealt with in the past. We are sending null to a parameter of isBeacon because it does not specify its nullity and the vanilla implementation doesn't use it. Kotlin then assumes it should be nonnull, thus causing a crash. I'm not sure what the best solution for this is, I don't believe my usage context has the information to send those parameters correctly (can't look right now)

**Comment by ejektaflex** [comment]
@primetoxinz I can change the said parameter to be nullable and do a Kotlin null safety check, that should be the fix for it. I'll update you if I need anything else.

The problem is that when creating a Kotlin override for a Java method, Mojang never specified said parameters as nonnull so as Kotlin developers we don't know whether to make the parameter nullable (In most cases we should assume it can be null but the code author figured incorrectly that the world param would always exist).

**Comment by matyklug18** [comment]
i got the same crash.
